---
title: "Índices de Moran"
author: "Juan Guillermo Narvaez"
date: "12/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio Materia Orgánica

```{r}
library(ape)
set.seed(12345)
MO <- rnorm(n = 150,mean = 3,sd = 0.5)
xy <- expand.grid(x=seq(1,10),y=seq(1,15))

plot(xy,col=MO,pch=19)
```

```{r}
as.data.frame(MO)
xymatrix <- as.matrix(dist(cbind(xy$x, xy$y)))
xymatrix_inv <- 1/xymatrix
diag(xymatrix_inv) <- 0
xymatrix_inv[1:10, 1:10]
Moran.I(MO, xymatrix_inv)
```


## Ejercicio Conductividad Eléctrica

```{r}
library(readxl)
BD_MORAN_1_ <- read_excel("D:/Kevin/Trabajos/Computacion estadistica/BD_MORAN (1).xlsx")
#View(BD_MORAN_1_)
head(BD_MORAN_1_, n=20)

```

```{r}
Longitud <- BD_MORAN_1_$X_WGS84
Latitud <- BD_MORAN_1_$Y_WGS84  
plot(Longitud,Latitud,col ="blue",cex = 0.2,main = "Gráfico de Puntos de muestra")
```
```{r}
Longitud <- BD_MORAN_1_$X_WGS84
Latitud <- BD_MORAN_1_$Y_WGS84  
plot(Longitud,Latitud,col =BD_MORAN_1_$CEa_075,cex = 0.5,main = "Conductividad Eléctrica a 75cm de profundidad")
```

### Índice de Moran - CE a 75cm [primeras 5000 muestras]

```{r}
library(ape)
Longitud <- BD_MORAN_1_$X_WGS84[1:5000]
Latitud <- BD_MORAN_1_$Y_WGS84[1:5000]
Ce_dist <- as.matrix(dist(cbind(Longitud, Latitud)))
dim(Ce_dist)

Ce_dist_inv <- 1/Ce_dist
Ce_dist_inv[is.infinite(Ce_dist_inv)] <- 0
diag(Ce_dist_inv) <- 0
CEa_075_1 <- BD_MORAN_1_$CEa_075[1:5000]
Ce_dist_inv[1:10,1:10]

Moran.I(CEa_075_1,Ce_dist_inv)
```

### Índice de Moran - CE a 75cm [de la muestra 5001 a la 10000]

```{r}
library(ape)
Longitud <- BD_MORAN_1_$X_WGS84[5001:10000]
Latitud <- BD_MORAN_1_$Y_WGS84[5001:10000]
Ce_dist <- as.matrix(dist(cbind(Longitud, Latitud)))
dim(Ce_dist)

Ce_dist_inv <- 1/Ce_dist
Ce_dist_inv[is.infinite(Ce_dist_inv)] <- 0
diag(Ce_dist_inv) <- 0
CEa_075_1 <- BD_MORAN_1_$CEa_075[5001:10000]
Ce_dist_inv[1:10,1:10]

Moran.I(CEa_075_1,Ce_dist_inv)
```

### Índice de Moran - CE a 75cm [de la muestra 10001 a la 18526]

```{r}
library(ape)
Longitud <- BD_MORAN_1_$X_WGS84[10001:18526]
Latitud <- BD_MORAN_1_$Y_WGS84[10001:18526]
Ce_dist <- as.matrix(dist(cbind(Longitud, Latitud)))
dim(Ce_dist)

Ce_dist_inv <- 1/Ce_dist
Ce_dist_inv[is.infinite(Ce_dist_inv)] <- 0
diag(Ce_dist_inv) <- 0
CEa_075_1 <- BD_MORAN_1_$CEa_075[10001:18526]
Ce_dist_inv[1:10,1:10]

Moran.I(CEa_075_1,Ce_dist_inv)
```


```{r}
Longitud <- BD_MORAN_1_$X_WGS84
Latitud <- BD_MORAN_1_$Y_WGS84  
plot(Longitud,Latitud,col =BD_MORAN_1_$CEa_150,cex = 0.5,main = "Conductividad Eléctrica a 150cm de profundidad")
```

### Índice de Moran - CE a 150cm [primeras 5000 muestras]

```{r}
library(ape)
Longitud <- BD_MORAN_1_$X_WGS84[1:5000]
Latitud <- BD_MORAN_1_$Y_WGS84[1:5000]
Ce_dist <- as.matrix(dist(cbind(Longitud, Latitud)))
dim(Ce_dist)

Ce_dist_inv <- 1/Ce_dist
Ce_dist_inv[is.infinite(Ce_dist_inv)] <- 0
diag(Ce_dist_inv) <- 0
CEa_150_1 <- BD_MORAN_1_$CEa_150[1:5000]
Ce_dist_inv[1:10,1:10]

Moran.I(CEa_150_1,Ce_dist_inv)
```

### Índice de Moran - CE a 150cm [de la muestra 5001 a la 10000]

```{r}
library(ape)
Longitud <- BD_MORAN_1_$X_WGS84[5001:10000]
Latitud <- BD_MORAN_1_$Y_WGS84[5001:10000]
Ce_dist <- as.matrix(dist(cbind(Longitud, Latitud)))
dim(Ce_dist)

Ce_dist_inv <- 1/Ce_dist
Ce_dist_inv[is.infinite(Ce_dist_inv)] <- 0
diag(Ce_dist_inv) <- 0
CEa_150_1 <- BD_MORAN_1_$CEa_150[5001:10000]
Ce_dist_inv[1:10,1:10]

Moran.I(CEa_150_1,Ce_dist_inv)
```

### Índice de Moran - CE a 150cm [de la muestra 10001 a la 18526]

```{r}
library(ape)
Longitud <- BD_MORAN_1_$X_WGS84[10001:18526]
Latitud <- BD_MORAN_1_$Y_WGS84[10001:18526]
Ce_dist <- as.matrix(dist(cbind(Longitud, Latitud)))
dim(Ce_dist)

Ce_dist_inv <- 1/Ce_dist
Ce_dist_inv[is.infinite(Ce_dist_inv)] <- 0
diag(Ce_dist_inv) <- 0
CEa_150_1 <- BD_MORAN_1_$CEa_150[10001:18526]
Ce_dist_inv[1:10,1:10]

Moran.I(CEa_150_1,Ce_dist_inv)
```




